# Generated by Django 4.2.5 on 2023-09-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySQL_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
