# Generated by Django 4.2.5 on 2023-09-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySQL_CRUD', '0002_alter_registerform_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='registerform',
            table=None,
        ),
    ]
